services:

  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pregasen@146#
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Pregasen@146#' -Q 'SELECT 1' -No -C || exit 1"]
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 5s

  glms-backend-api:
    build:
      context: .
      dockerfile: Web_Api/Dockerfile
    container_name: glms-backend-api
    depends_on:
      sql-server-db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Server=sql-server-db;Database=NewApiProg3A;User Id=sa;Password=Pregasen@146#;TrustServerCertificate=True;MultipleActiveResultSets=true;
    ports:
      - "5084:8080"
    restart: on-failure

  glms-frontend-web:
    build:
      context: .
      dockerfile: ProjectPOE_Prog3A/Dockerfile
    container_name: glms-frontend-web
    depends_on:
      glms-backend-api:
        condition: service_started
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__ProjectPOE_Prog3AContext=Server=sql-server-db;Database=NewApiProg3A;User Id=sa;Password=Pregasen@146#;TrustServerCertificate=True;MultipleActiveResultSets=true;
    ports:
      - "8082:8080"
    restart: on-failure
    volumes:
      - uploads:/app/wwwroot/uploads

volumes:
  sqldata:
  uploads: