name: ReCenterHub CI/CD

on:
  push:
    branches:
      - main
      - diyaBranch

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-build

      - name: Publish API
        run: dotnet publish Api/Api.csproj --configuration Release --output ./publish/api

      - name: Publish ReCenterHub
        run: dotnet publish ReCenterHub/ReCenterHub.csproj --configuration Release --output ./publish/recenterhub